"""empty message

Revision ID: e72f25e48f23
Revises: 
Create Date: 2019-07-30 19:20:10.894823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72f25e48f23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweeter_user')
    op.create_unique_constraint('game_participants_id', 'game_participants', ['user_id', 'game_id'])
    op.create_unique_constraint('game_guesses', 'guess', ['tweet_guess_id', 'guess_twitter_user_id', 'user'])
    op.create_unique_constraint('user_category_uc', 'user_category', ['category_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_category_uc', 'user_category', type_='unique')
    op.drop_constraint('game_guesses', 'guess', type_='unique')
    op.drop_constraint('game_participants_id', 'game_participants', type_='unique')
    op.create_table('tweeter_user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=240), autoincrement=False, nullable=True),
    sa.Column('profile_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tweeter_user_pkey'),
    sa.UniqueConstraint('name', name='tweeter_user_name_key'),
    sa.UniqueConstraint('username', name='tweeter_user_username_key')
    )
    # ### end Alembic commands ###
